### ISSUE TITLE
CMSF2 Profile broken

### ISSUE THREAD

**Issue by Lorenzo6677** [DerButschi/CMAutoEditor#20]
**Describe the bug**
Running the OSM2CM.exe with the SF2 profiles loaded
Crashes program and gives no output file

Log
Processing Priority 5, Stage 1, processor process_residential_building_outlines:   0%|          | 0/30 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "osm2cm.py", line 573, in <module>
  File "osm2cm.py", line 467, in run_processors
  File "osm_utils\processing.py", line 1025, in process_residential_building_outlines
  File "osm_utils\processing.py", line 1090, in process_building_outlines
AttributeError: 'NoneType' object has no attribute 'is_diagonal'
[8260] Failed to execute script 'osm2cm' due to unhandled exception!

**To Reproduce**
Attempt to convert a file using the osm2cm and the SF2 Profiles

**Setup:**
 - OS: Windows 10
 - CMAutoEditor version: 2.2

**Screenshot**
Please provide a screenshot if possible. (Drag and drop to "Attach files by dragging & dropping ..." at the bottom of this issue text field)

**Additional context**

**Comment by DerButschi** [comment]
Looks like a simple typo (German vs English spelling...). Please try: https://github.com/DerButschi/CMAutoEditor/releases/tag/2.2.1
